
seed: &seed 3407
batch_size: &batch_size 1024
n_class: &n_class 5
n_epochs: &n_epochs 20
weight_decay: &weight_decay 1.0e-5


phases: [train, test]
info_step: 100
is_plot: False
disable_tb: True
disable_tqdm: False
metrics: [loss, top1_acc, top2_acc]


setup:
  model: CNN-64
  model_name: Nominal
  optimizer: radam
  lr_scheduler: warmup_cosine_decay_schedule
  loss: cb_ce_loss
  dataset: nominal
  n_class: *n_class
  seed: *seed
  n_epochs: *n_epochs
  workdir: result
  mixed_precision: False
  smooth_label: null
  weight_decay: *weight_decay

mp_policy: 
  nonfinite: True
  init_val: 32768 #2**15


optimizer:
  opts:
    clip_by_global_norm: {max_norm: 1.0}
  radam: {b1: 0.90, b2: 0.999}

lr_scheduler:
  warmup_cosine_decay_schedule: 
    init_value: 1.0e-5
    peak_value: 1.0e-2
    warmup_steps: 5
    decay_steps: *n_epochs
    end_value: 1.0e-6
    
loss:
  cb_ce_loss: {beta: 0.999, gamma: -2.0}
  ce_loss: None
  

dataset:
  data_name: nominal
  batch_size: *batch_size
  split: 
    N: 20
    idx: 1
  n_prefetch: 2
  transpose: True
  cache: False
  prop_table: [0, 4, 5]
  label_table: [7, 1, 1, 2, 3, 4, 0] # [None, d, u, s, c, b, g]
  
FiLM : &FiLM {depth: 16, dim: 4, dim_inner: 4, norm: null, activation: null, dropout: null}
#FiLM : &FiLM null

hparams:
  FiLM: *FiLM
  weight_decay: *weight_decay
  setup: [loss, model, lr_scheduler, optimizer]


model:
  ViT-VT/16:   {patch_size: 4, depth:  4, dim:   64, expansion: 4, n_heads:    4, dropout: null, drop_path: null, layer_scale: null, qkv_bias: False, n_classes: *n_class, film: *FiLM}
  ViT-S/16:    {patch_size: 4, depth: 12, dim:  384, expansion: 4, n_heads:    6, dropout: null, drop_path: null, layer_scale: null, qkv_bias: False, n_classes: *n_class, film: *FiLM}
  ViT-B/16:    {patch_size: 4, depth: 12, dim:  768, expansion: 4, n_heads:   12, dropout: null, drop_path: null, layer_scale: null, qkv_bias: False, n_classes: *n_class, film: *FiLM}
  Mixer-T/16:  {patch_size: 4, depth: 16, dim:  128, expansion: 4,                dropout:  0.1, drop_path:  0.1, layer_scale: 1.0e-5,                n_classes: *n_class, film: *FiLM}
  Mixer-VT/16: {patch_size: 4, depth:  4, dim:   64, expansion: 4,                dropout: null, drop_path: null, layer_scale: null,                  n_classes: *n_class, film: *FiLM}
  Mixer-S/16:  {patch_size: 4, depth: 12, dim:  384, expansion: 4,                dropout: null, drop_path: null, layer_scale: null,                  n_classes: *n_class, film: *FiLM}
  Mixer-B/16:  {patch_size: 4, depth: 12, dim:  768, expansion: 4,                dropout: null, drop_path: null, layer_scale: null,                  n_classes: *n_class, film: *FiLM}
  GoB-VT/16:   {patch_size: 4, depth:  4, dim:   64, expansion: 4, n_heads:    4, dropout: null, drop_path: null, layer_scale: null, qkv_bias: False, n_classes: *n_class, film: *FiLM}
  GoB-S/16:    {patch_size: 4, depth: 12, dim:  384, expansion: 4, n_heads:    6, dropout: null, drop_path: null, layer_scale: null, qkv_bias: False, n_classes: *n_class, film: *FiLM}
  GoB-B/16:    {patch_size: 4, depth: 12, dim:  768, expansion: 4, n_heads:   12, dropout: null, drop_path: null, layer_scale: null, qkv_bias: False, n_classes: *n_class, film: *FiLM}
  gMLP-T/16:   {patch_size: 4, depth: 16, dim:  128, expansion: 4, n_heads:    4, dropout:  0.1, drop_path:  0.1, layer_scale: 1.0e-5,                n_classes: *n_class, film: *FiLM}
  gMLP-VT/16:  {patch_size: 4, depth:  4, dim:   64, expansion: 4, n_heads:    4, dropout: null, drop_path: null, layer_scale: null,                  n_classes: *n_class, film: *FiLM}
  
  CNN-64: {dim: 64, patch_size: 16, n_classes: *n_class}
  Test: {dim: 64, patch_size: 16, n_classes: *n_class}
